### PR TITLE
deleted layEgg Method, updated yeild for if firtilized it lays fertil…

### PR DESCRIPTION
**Pull request by NaiyaJS**
chicken class deleted layEgg method and updated the Edible yield

### CODE REVIEW

**Review by kcj100 — CHANGES_REQUESTED** [review]
- For chicken, pass in a parameter (just make a another parameter after String name that's a boolean) within the constructor the assigns hasBeenFertilized to the boolean value (true or false, whatever is passed into the constructor during the object creation).

- For Horse, remember to fill out the setInUse method to change the inUse field to the available parameter.

- Also, in Chicken, remember to set the hasBeenFertilized field back to true after yield is called and the condition of !hasBeenFertilized goes through (meaning that an egg was yielded and hasBeenFertilized will be set to true)

**Comment by NaiyaJS** [comment]
added boolean to constructor and reset to true in yield

**Review by kcj100 — CHANGES_REQUESTED** [review]
One more thing is to delete the second dependency from pom.xml (line 23 to line 28) since we already have the junit dependency above

**Comment by NaiyaJS** [comment]
deleted extra dependency in pom.xml

**Pull request merged**
