### PR TITLE
makeNoise methods and interface changed

### PR DESCRIPTION
**Pull request by NaiyaJS**
changes to make noise method and interface

### CODE REVIEW

**Comment by NaiyaJS** [comment]
added chicken test cases, commented out makeNose() in chicken class

**Comment by NaiyaJS** [comment]
in horse class finished the inUse and setInUse

**Review by kcj100 — CHANGES_REQUESTED** [review]
- Add space between the quote and "is" within the eat method of Animal on line 32. 

- Add spaces in both sout statements in Chicken yield() between quotes and "has"

**Comment by NaiyaJS** [comment]
added space before is in Animal class on line 32

**Comment by NaiyaJS** [comment]
added horse test cases not sure if testIsInUse should be assertTrue or false and with testsetInUse

**Comment by NaiyaJS** [comment]
added spaces to print out statements in chicken

**Comment by NaiyaJS** [comment]
change horse caps in test

**Comment by NaiyaJS** [comment]
add eggTests and isEdible method to egg class

**Comment by NaiyaJS** [comment]
added testImplementation for Animal Test class

**Pull request merged**
